#配置tomcat服务器信息，如果用默认就不用配置
#http://127.0.0.1:8080/CRM...
server:
  port: 8080   #端口号
  servlet:
    context-path: /CRM   #站点根路径
    
#配置http请求编码，默认是utf-8,可不配
spring:
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
      
#配置使用jsp作为视图技术，默认是theamleaf视图技术，需要配置
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
      
#配置连接数据库的连接信息
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.43.159:1521:orcl
   #如果需要链接本地的数据库，把上面url注释，下面url放开，注意：改后千万不要提交此文件
   #url: jdbc:oracle:thin:@localhost:1521:orcl
    username: CRM
    password: CRM
    
#读取mybatis配置文件
mybatis:
  config-location: classpath:config.xml
    
